steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'infrastructure/docker/Dockerfile.cloudrun', '-t', 'gcr.io/$PROJECT_ID/lab-lens-web', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lab-lens-web']

images:
  - 'gcr.io/$PROJECT_ID/lab-lens-web'

timeout: 1200s  # 20 minutes
